---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: bishy
  image: alpine:latest
  commands:
  - apk add --no-cache sudo bash
  - bash -c "source bishy.bash"

- name: setup
  image: alpine:latest
  commands:
  - apk add --no-cache sudo bash
  - bash -c "source setup.bash"
